version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: hotel_db
      MYSQL_USER: h_user
      MYSQL_PASSWORD: h_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
#      - wird sichergestellt, dass das init.sql-Skript beim Erstellen des Containers ausgeführt wird

volumes:
  db_data:
